DECLARE
    FEET NUMBER;
    INCH NUMBER;
    CM NUMBER;
    METER NUMBER;
BEGIN
    FEET:=&FEET;
    INCH:=FEET*12;
    CM:=FEET*30.48;
    METER:=FEET*0.3048;

    DBMS_OUTPUT.PUT_LINE('FEET:'||FEET);
    DBMS_OUTPUT.PUT_LINE('INCH:'||INCH);
    DBMS_OUTPUT.PUT_LINE('CENTY METER:'||CM);
    DBMS_OUTPUT.PUT_LINE('METER:'||METER);
END;
/
